<?php

namespace Pachico\Abtest\Tracking;

use \Pachico\Abtest\Test,
	\Pachico\Abtest\Split,
	\Mockery as m;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-03-26 at 14:55:25.
 */
class GoogleExperimentsTest extends \PHPUnit_Framework_TestCase
{

	/**
	 * @var GoogleExperiments
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = new GoogleExperiments(false);
	}

	/**
	 * @covers Pachico\Abtest\Tracking\GoogleExperiments::track
	 * @covers Pachico\Abtest\Tracking\GoogleExperiments::__construct
	 */
	public function testTrack()
	{
		$mocked_memory = m::mock('\Pachico\Abtest\Memory\MemoryInterface');
		$mocked_memory->shouldReceive('getVersion')->once()->andReturn(1);
		$mocked_memory->shouldReceive('getVersion')->once()->andReturn(0);

		$test1 = new Test\Test('foo', new Split\ArrayProbability([50, 50]), $mocked_memory, null, 'foo_tracking_id');
		$test2 = new Test\Test('bar', new Split\ArrayProbability([50, 50]), $mocked_memory, null, 'bar_tracking_id');

		$tests = [$test1, $test2];

		$tracking = "<script>cxApi.setChosenVariation(1, 'foo_tracking_id');</script>\n"
			. "<script>cxApi.setChosenVariation(0, 'bar_tracking_id');</script>";

		$this->assertSame(
			$tracking, $this->object->track($tests)
		);

		$tracking = "<script src=\"//www.google-analytics.com/cx/api.js\"></script>\n"
			. $tracking;

		$this->object = new GoogleExperiments(true);

		$this->assertSame(
			$tracking, $this->object->track($tests)
		);
	}

}
