<?php

namespace Pachico\Abtest;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-03-26 at 15:48:29.
 */
class EngineTest extends \PHPUnit_Framework_TestCase
{

	/**
	 * @var Engine
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		//$this->object = new Engine;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
		
	}

	/**
	 * @covers Pachico\Abtest\Engine::getSingleton
	 * @todo   Implement testGetSingleton().
	 */
	public function testGetSingleton()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Pachico\Abtest\Engine::getTest
	 * @todo   Implement testGetTest().
	 */
	public function testGetTest()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Pachico\Abtest\Engine::getMemory
	 * @todo   Implement testGetMemory().
	 */
	public function testGetMemory()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Pachico\Abtest\Engine::getTracking
	 * @todo   Implement testGetTracking().
	 */
	public function testGetTracking()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

}
