<?php

namespace Pachico\Abtest;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-03-25 at 18:34:43.
 */
class EngineTest extends \PHPUnit_Framework_TestCase
{

	/**
	 * @var Engine
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		//$this->object = new Engine;
	}

	public function testHappyPath()
	{
		$abtest_config = new Config\FromFile(__DIR__ . '/../config/config1.php');

//		$ab_memory = new Memory\Memory();
//		$ab_tracking = new Tracking\GoogleExperiments();
//
//		$ab_engine = new Engine($ab_config, $ab_memory, $ab_tracking);

		$abtest_engine = new Engine($abtest_config);

		$test_foo = $abtest_engine->getTest('TEST_FOO');

		$is_participant = $test_foo->isParticipant();

		//var_dump($is_participant);

		//$version = $test_foo->getVersion();
	}

}
